Repository AreaLayer/javascript-dlc, pull requests merged in 2023-11, with the labels that each got.

#16 Update settings.default.yml
  settings.default.yml
Labels: documentation, enhancement, help wanted, Epic

#13 Add Clean documentation
  docs/development.md
Labels: documentation, Epic

#15 Add Changelog about versions launched
  CHAGELOG.md
Labels: enhancement, help wanted, Epic
